package be.contribute.exceptionhandling.model;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 09:56:17 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExceptionAMImpl
	extends ApplicationModuleImpl
{
	/**
	 * This is the default constructor (do not remove).
	 */
	public ExceptionAMImpl()
	{
	}

	/**
	 * Container's getter for JobsVOVI.
	 * @return JobsVOVI
	 */
	public JobsVOImpl getJobsVOVI()
	{
		return (JobsVOImpl)findViewObject("JobsVOVI");
	}
}

