package be.contribute.exceptionhandling.model;

import be.contribute.exceptionhandling.model.exceptions.CustomJboException;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 09:55:38 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobsVOImpl
	extends ViewObjectImpl
{
	/**
	 * This is the default constructor (do not remove).
	 */
	public JobsVOImpl()
	{
	}
	
	public void failOnJobVO()
	{
		throw new CustomJboException("Failed on JobVO");
	}
}

