package be.contribute.exceptionhandling.model.viewobjects.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:23:10 CET 2016
// ---------------------------------------------------------------------
public interface JobsVORow
	extends Row
{
	void failOnJobRow();
}

