package be.contribute.exceptionhandling.model.viewobjects.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:47:44 CET 2016
// ---------------------------------------------------------------------
public interface RegionsVO
	extends ViewObject
{
	void failOnRegionsVO();
}

