package be.contribute.exceptionhandling.model.viewobjects.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:47:49 CET 2016
// ---------------------------------------------------------------------
public interface RegionsVORow
	extends Row
{
	void failOnRegionsVORow();
}

