package be.contribute.exceptionhandling.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:23:22 CET 2016
// ---------------------------------------------------------------------
public interface ExceptionAM
	extends ApplicationModule
{
	void throwCustomJboException();

	void throwCustomRuntimeException();
}

