package be.contribute.exceptionhandling.model.viewobjects;

import be.contribute.exceptionhandling.model.entities.CountriesImpl;
import be.contribute.exceptionhandling.model.exceptions.CustomJboException;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 13:12:31 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountriesVORowImpl
	extends ViewRowImpl
{
	public static final int ENTITY_COUNTRIES = 0;

	/**
	 * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
	 */
	public enum AttributesEnum
	{
		CountryId,
		CountryName,
		RegionId;
		private static AttributesEnum[] vals = null;
		private static final int firstIndex = 0;

		public int index()
		{
			return AttributesEnum.firstIndex() + ordinal();
		}

		public static final int firstIndex()
		{
			return firstIndex;
		}

		public static int count()
		{
			return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
		}

		public static final AttributesEnum[] staticValues()
		{
			if (vals == null)
			{
				vals = AttributesEnum.values();
			}
			return vals;
		}
	}
	public static final int COUNTRYID = AttributesEnum.CountryId.index();
	public static final int COUNTRYNAME = AttributesEnum.CountryName.index();
	public static final int REGIONID = AttributesEnum.RegionId.index();

	/**
	 * This is the default constructor (do not remove).
	 */
	public CountriesVORowImpl()
	{
	}

	/**
	 * Gets Countries entity object.
	 * @return the Countries
	 */
	public CountriesImpl getCountries()
	{
		return (CountriesImpl)getEntity(ENTITY_COUNTRIES);
	}

	/**
	 * Gets the attribute value for COUNTRY_ID using the alias name CountryId.
	 * @return the COUNTRY_ID
	 */
	public String getCountryId()
	{
		return (String)getAttributeInternal(COUNTRYID);
	}

	/**
	 * Sets <code>value</code> as attribute value for COUNTRY_ID using the alias name CountryId.
	 * @param value value to set the COUNTRY_ID
	 */
	public void setCountryId(String value)
	{
		setAttributeInternal(COUNTRYID, value);
	}

	/**
	 * Gets the attribute value for COUNTRY_NAME using the alias name CountryName.
	 * @return the COUNTRY_NAME
	 */
	public String getCountryName()
	{
		return (String)getAttributeInternal(COUNTRYNAME);
	}

	/**
	 * Sets <code>value</code> as attribute value for COUNTRY_NAME using the alias name CountryName.
	 * @param value value to set the COUNTRY_NAME
	 */
	public void setCountryName(String value)
	{
		setAttributeInternal(COUNTRYNAME, value);
	}

	/**
	 * Gets the attribute value for REGION_ID using the alias name RegionId.
	 * @return the REGION_ID
	 */
	public BigDecimal getRegionId()
	{
	   throw new CustomJboException("Could not get region id");
		//return (BigDecimal)getAttributeInternal(REGIONID);
	}

	/**
	 * Sets <code>value</code> as attribute value for REGION_ID using the alias name RegionId.
	 * @param value value to set the REGION_ID
	 */
	public void setRegionId(BigDecimal value)
	{
	   throw new CustomJboException("Could not set region id");
		//setAttributeInternal(REGIONID, value);
	}
}

