package be.contribute.exceptionhandling.model.viewobjects;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 12:07:55 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesJboVORowImpl
	extends ViewRowImpl
{
	/**
	 * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
	 */
	public enum AttributesEnum
	{
		EmployeeId,
		FirstName,
		LastName,
		Email,
		ExceptionType;
		private static AttributesEnum[] vals = null;
		private static final int firstIndex = 0;

		public int index()
		{
			return AttributesEnum.firstIndex() + ordinal();
		}

		public static final int firstIndex()
		{
			return firstIndex;
		}

		public static int count()
		{
			return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
		}

		public static final AttributesEnum[] staticValues()
		{
			if (vals == null)
			{
				vals = AttributesEnum.values();
			}
			return vals;
		}
	}
	public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
	public static final int FIRSTNAME = AttributesEnum.FirstName.index();
	public static final int LASTNAME = AttributesEnum.LastName.index();
	public static final int EMAIL = AttributesEnum.Email.index();
	public static final int EXCEPTIONTYPE = AttributesEnum.ExceptionType.index();

	/**
	 * This is the default constructor (do not remove).
	 */
	public EmployeesJboVORowImpl()
	{
	}

	/**
	 * Gets the attribute value for the calculated attribute EmployeeId.
	 * @return the EmployeeId
	 */
	public Integer getEmployeeId()
	{
		return (Integer)getAttributeInternal(EMPLOYEEID);
	}

	/**
	 * Gets the attribute value for the calculated attribute FirstName.
	 * @return the FirstName
	 */
	public String getFirstName()
	{
		return (String)getAttributeInternal(FIRSTNAME);
	}

	/**
	 * Gets the attribute value for the calculated attribute LastName.
	 * @return the LastName
	 */
	public String getLastName()
	{
		return (String)getAttributeInternal(LASTNAME);
	}

	/**
	 * Gets the attribute value for the calculated attribute Email.
	 * @return the Email
	 */
	public String getEmail()
	{
		return (String)getAttributeInternal(EMAIL);
	}

	/**
	 * Gets the attribute value for the calculated attribute ExceptionType.
	 * @return the ExceptionType
	 */
	public String getExceptionType()
	{
		return (String)getAttributeInternal(EXCEPTIONTYPE);
	}
}

