package be.contribute.exceptionhandling.model.viewobjects;

import be.contribute.exceptionhandling.model.exceptions.CustomJboException;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 12:07:55 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesJboVOImpl
	extends ViewObjectImpl
{
	/**
	 * This is the default constructor (do not remove).
	 */
	public EmployeesJboVOImpl()
	{
	}


	@Override
	protected void executeQueryForCollection(Object pObject, Object[] object2, int i)
	{
		throw new CustomJboException("Jbo while executing query");
		//super.executeQueryForCollection(pObject, object2, i);
	}
}

