package be.contribute.exceptionhandling.model.viewobjects;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:59:06 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class JobHistoryVOImpl
	extends ViewObjectImpl
{
	/**
	 * This is the default constructor (do not remove).
	 */
	public JobHistoryVOImpl()
	{
	}
}

