package be.contribute.exceptionhandling.model.viewobjects;

import be.contribute.exceptionhandling.model.exceptions.CustomRuntimeException;
import be.contribute.exceptionhandling.model.viewobjects.common.RegionsVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:33:00 CET 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionsVOImpl
	extends ViewObjectImpl
	implements RegionsVO
{
	/**
	 * This is the default constructor (do not remove).
	 */
	public RegionsVOImpl()
	{
	}
	
	
	public void failOnRegionsVO()
	{
		throw new CustomRuntimeException("Fail on Regions VO");
	}
	
}

